feat: v0.5.0-alpha.1 (#110)
* feat: enhance Build and BuildAndPublish functions with versioning and git commit annotations

* chore: bump semver to v0.5.0-alpha1

* docs: hide repetitive lines in snippets

* refactor: reorder builder initialization in Build function for clarity

* chore: update dagger version to 0.20.3 across workflows and configuration

* refactor: streamline E2E_Test and TestWithCoverage functions by integrating git repository parameter and cleaning up comments

* wip

* feat: implement Untar functionality and corresponding tests for extracting files from tar archives

* refactor: enhance Untar function with path sanitization and improve directory permissions

* fix: ensure directory creation for resourcesPath with proper permissions

* build: adding containerfile definition for non dagger build

cherry-pick origin/container-build

* build: adding containerfile definition for non dagger build

cherry-pick origin/container-build

* build: update Containerfile

* fix: remove default values for GOOS and GOARCH in Containerfile

* fix: build pipeline

* fix: untar tests

* refactor: default cue resources path

* fix: untar tests

* ci: fix main tag

* ci: parametrise platforms and add image refresh

* ci: remove unused function

---------

Co-authored-by: David Lynch <davite3@protonmail.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -13,24 +13,23 @@ jobs:
       TAG: ${{ github.event.release.tag_name }}
 
     outputs:
-      tag_name: ${{ steps.generate-tag-name.outputs.tag }}
+      version: ${{ steps.get-version.outputs.version }}
       latest: ${{ steps.set-latest.outputs.latest }}
 
     steps:
-    - name: Tag Follows SemVer
+    - name: Version Follows SemVer
       run: |
-        if [[ ! "${TAG}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-(alpha|rc)\.[0-9]+)?$ ]]; then
-          echo "Invalid SemVer tag: ${TAG}" >&2
+        if [[ ! "${TAG}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[\w.]+)?$ ]]; then
+          echo "Invalid SemVer: ${TAG}" >&2
           exit 1
         fi
 
-    - name: Generate Tag Name
-      id: generate-tag-name
+    - name: Get Version
+      id: get-version
       run: |
-        # remove v prefix
-        IMAGE_TAG=${TAG#v}
+        VERSION=${TAG}
 
-        echo -n "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
+        echo -n "version=${VERSION}" >> $GITHUB_OUTPUT
 
     # only tag as latest if the release is set to latest
     - name: set tag as latest
@@ -58,13 +57,14 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GITHUB_USER: ${{ github.actor }}
-        TAG: ${{ needs.prep.outputs.tag_name }}
+        VERSION: ${{ needs.prep.outputs.version }}
         LATEST: ${{ needs.prep.outputs.latest }}
         REPOSITORY: workday/cuestomize
+        PLATFORMS: linux/amd64,linux/arm64
       with:
-        version: "0.20.1"
+        version: "0.20.3"
         verb: call
-        args: build-and-publish --repository="$REPOSITORY" --tag="$TAG" --also-tag-as-latest="$LATEST" --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --platforms=linux/amd64,linux/arm64
+        args: build-and-publish --repository="$REPOSITORY" --version="$VERSION" --latest="$LATEST" --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --platforms="$PLATFORMS"
 
   publish-examples:
     name: Publish Examples
@@ -83,9 +83,9 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GITHUB_USER: ${{ github.actor }}
         REPOSITORY_PREFIX: ${{ github.repository }}/cuemodules/cuestomize-examples
-        TAG: ${{ needs.prep.outputs.tag_name }}
+        VERSION: ${{ needs.prep.outputs.version }}
         LATEST: ${{ needs.prep.outputs.latest }}
       with:
-        version: "0.20.1"
+        version: "0.20.3"
         verb: call
-        args: publish-examples --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --tag="$TAG" --latest="$LATEST" --repositoryPrefix="$REPOSITORY_PREFIX"
+        args: publish-examples --username="$GITHUB_USER" --password=env:GITHUB_TOKEN --version="$VERSION" --latest="$LATEST" --repositoryPrefix="$REPOSITORY_PREFIX"
